# Generated by Django 5.0.4 on 2024-05-02 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='note',
            table='note',
        ),
    ]
